const QuestionActions = {
  ADDED_QUESTION: "ADDED_QUESTION",
  HANDLED_QUESTION: "HANDLED_QUESTION",
  REMOVED_QUESTION: "REMOVED_QUESTION",
  EDITED_QUESTION: "EDITED_QUESTION",
};

export default QuestionActions;
