const QuestionActions = {
  ADDED_QUESTION: "ADDED_QUESTION",
  FETCHED_QUESTIONS: "FETCHED_QUESTIONS",
  HANDLED_QUESTION: "HANDLED_QUESTION",
  REMOVED_QUESTION: "REMOVED_QUESTION",
  EDITED_QUESTION: "EDITED_QUESTION",
  INTERMEDIATE: "INTERMEDIATE",
};

export default QuestionActions;
